controller_manager:
  ros__parameters:
    update_rate: 10
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController
    
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    publish_rate: 10.0
    base_frame_id: base_link
    wheels_per_side: 2
    left_wheel_names: ["backLeft_joint", "frontLeft_joint"]
    right_wheel_names: ["backRight_joint", "frontRight_joint"]
    wheel_separation: .203
    wheel_radius: .024
    

    use_stamped_vel: false


joint_broad:
  ros__parameters:
    joints: ["backLeft_joint", "frontLeft_joint", "backRight_joint", "frontRight_joint"]